name: CI

on:
  push:
    branches:
      - main

jobs:
  call-build-workflow:
    uses: bakeryos-project/ci/.github/workflows/build-package.yml@main
    secrets:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
